### ISSUE TITLE
sfCacheException error

### ISSUE THREAD

**Issue by scheffman** [deStrO/eBot-CSGO-Web#51]
Hi, great work.

but i have run in to a problem, ebot works. But ebot web panel dont. here is the error from apache2/error.log

![virtualbox_ebot server_29_01_2016_16_54_53](https://cloud.githubusercontent.com/assets/16961223/12682855/094f052a-c6b6-11e5-8c34-41c7c643c43a.png)

Maybe i have copied eBot-Web wrong. Can you pleas tell me how to copy the files to my /var/www folder? i have tryd diffrent ways to link it. Some of the ways i have tryed: "cp -a ebot-web /var/www/html" "cp -a ebot-web /var/www/" "ln -sf ebot-web /var/www/html".

Thanks for answers!

**Comment by excalibur3000** [comment]
Same sometimes for me. It is a little bit strange that Webpanel doesn't uses folder html too. So apache config must be changed.

Best regards
Christian

**Comment by scheffman** [comment]
Yeah, i found the solution, i did "$ sudo ln -sf /usr/share/ebot-web/web /var/www/html"(Move or delete the old html folder) then "$ sudo chmod root:www-data /usr/share/ebot-web/cache" and it worked. You can make a chmod on the html to.

But on the other note i got the web panel to open and the websocket at loaded. But there are some other things like i cant revome servers in server manager, im gonna digg around a little and se if i can find a solusion.

Sorry for bad English im from Sweden.

**Comment by scheffman** [comment]
Just whant to confirm that i got ebot and the panel working now. By folowing [https://github.com/deStrO/eBot-CSGO/blob/threads/install.txt](url) and did the above. note remeber the CSay addon and add exctension=pthread.so to the right php.ini file.

Great work and will be looking forward to ebot 4.0.

This can be closed. @deStrO

**Comment by excalibur3000** [comment]
Am 01.02.2016 um 19:34 schrieb scheffman:
>
> Just whant to confirm that i got ebot and the panel working now. By 
> folowing https://github.com/deStrO/eBot-CSGO/blob/threads/install.txt 
> <url> and did the above. note remeber the CSay addon and add 
> exctension=pthread.so to the right php.ini file.
>
> Great work and will be looking forward to ebot 4.0.
>
> This can be closed. @deStrO <https://github.com/deStrO>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/deStrO/eBot-CSGO-Web/issues/51#issuecomment-178114527>.
>
Hi,

can you plz give me your e-mail address? Mine is "christian@myexcalibur.de"

I have still the problem, that i can't see anything when i open 
"admin.php". Rest is working also the installation routine.

Best regards from germany
Christian

**Comment by scheffman** [comment]
Hi, check your apache/error.log

Make sure your apache user have premisions to the web files and the cache file. _$ sudo chown www-data /path/to/file_ if you do this on a folder use _-R_ for recursive, so your files also get the premision. Do it on the _cache_,_web_ and the files in the web folder. And test to clear symphony cache _$ sudo php symphony cc_.

Please in the future submit the error you get, else its hard to help.

Best regards from Sweden.

**Comment by excalibur3000** [comment]
Am 02.02.2016 um 17:16 schrieb scheffman:
> /chown www-data/
Hello,

i have tested a lot and nearly everything is working fine. I can start 
and manage games now, really nice. But 2 things seem not to work.
1. Gameserver won't start with a config selected, although added in 
Config Management and uploaded on server
2. My "index.php" doesn't work. Admin.php is working fine, seems as 
index.php is not allowed (only white screen).

Best regards
Christian

**Comment by scheffman** [comment]
The only thing i can think of is permissions. For the gameserver make sure you have the CSay addon in _.../steamcmd/.go/csgo/addons_ also make sure you have the right rcon password and when you start a game on the gameserver whit _srcds_run_ user _+ip 192.0.1.2_ (but your ip) i had that problem. 

Best regards

**Comment by excalibur3000** [comment]
Am 03.02.2016 um 10:32 schrieb scheffman:
>
> The only thing i can think of is permissions. For the gameserver make 
> sure you have the CSay addon in /.../steamcmd/.go/csgo/addons/ also 
> make sure you have the right rcon password and when you start a game 
> on the gameserver whit /srcds_run/ user /+ip 192.0.1.2/ (but your ip) 
> i had that problem.
>
> Best regards
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/deStrO/eBot-CSGO-Web/issues/51#issuecomment-179121510>.
>
Can u access the index.php on your webserver? Is it like the one on 
http://public.ebot.wedeho.be/ ?

Do you use Steam?

**Comment by scheffman** [comment]
@excalibur3000 yes the index.php looks like that, its for non admin users to view matches and stats. If the index.php is blank look in you apache error log, or download it again if its corrupt. If you get a not allowed you have the wrong permission on the file or folder.

For the csgo server i user a steam account to install the server. For the game config i used gamemode_competetive.cfg when i create a match. I did it in virtualbox and had the servers on diffrent ip's.

**Comment by excalibur3000** [comment]
Am 03.02.2016 um 13:04 schrieb scheffman:
>
> @excalibur3000 <https://github.com/excalibur3000> yes the index.php 
> looks like that, its for non admin users to view matches and stats. If 
> the index.php is blank look in you apache error log, or download it 
> again if its corrupt. If you get a not allowed you have the wrong 
> permission on the file or folder.
>
> For the csgo server i user a steam account to install the server. For 
> the game config i used gamemode_competetive.cfg when i create a match. 
> I did it in virtualbox and had the servers on diffrent ip's.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/deStrO/eBot-CSGO-Web/issues/51#issuecomment-179188010>.
>
Thanks, now everything is working except the right configs. I will try 
if i can manage this too.

Christian

**Comment by excalibur3000** [comment]
Am 03.02.2016 um 14:32 schrieb Christian Feldmann:
> Am 03.02.2016 um 13:04 schrieb scheffman:
>>
>> @excalibur3000 <https://github.com/excalibur3000> yes the index.php 
>> looks like that, its for non admin users to view matches and stats. 
>> If the index.php is blank look in you apache error log, or download 
>> it again if its corrupt. If you get a not allowed you have the wrong 
>> permission on the file or folder.
>>
>> For the csgo server i user a steam account to install the server. For 
>> the game config i used gamemode_competetive.cfg when i create a 
>> match. I did it in virtualbox and had the servers on diffrent ip's.
>>
>> —
>> Reply to this email directly or view it on GitHub 
>> <https://github.com/deStrO/eBot-CSGO-Web/issues/51#issuecomment-179188010>.
>>
> Thanks, now everything is working except the right configs. I will try 
> if i can manage this too.
>
> Christian
Hello,

ebot works. Only one error left. Possibly u know about it and a solution.

/home/ebot/ebot-csgo/node_modules/socket.io/node_modules/socket.io-adapter/index.js:195
   if (fn) process.nextTick(fn.bind(null, null, sids));
                               ^
TypeError: undefined is not a function
     at Adapter.clients 
(/home/ebot/ebot-csgo/node_modules/socket.io/node_modules/socket.io-adapter/index.js:195:31)
     at Namespace.clients 
(/home/ebot/ebot-csgo/node_modules/socket.io/lib/namespace.js:253:16)
     at Socket.<anonymous> (/home/ebot/ebot-csgo/websocket_server.js:139:28)
     at Socket.emit (events.js:107:17)
     at Socket.emit 
(/home/ebot/ebot-csgo/node_modules/socket.io/lib/socket.js:128:10)
     at Socket.onclose 
(/home/ebot/ebot-csgo/node_modules/socket.io/lib/socket.js:425:8)
     at Client.onclose 
(/home/ebot/ebot-csgo/node_modules/socket.io/lib/client.js:232:24)
     at Socket.emit (events.js:129:20)
     at Socket.onClose 
(/home/ebot/ebot-csgo/node_modules/socket.io/node_modules/engine.io/lib/socket.js:304:10)
     at WebSocket.g (events.js:199:16)

The error occures if i went from "RCON/Backup" of a server to another 
menu-point.

Best regards
Christian
